# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  levels: two
  folders:

  - title: About
    output: web, pdf
    folderitems:

    - title: About
      output: web, pdf
      url: /about.html

    - title: Curriculum Vitae
      output: web, pdf
      url: /curriculum_vitae.html

  - title: Posts
    output: web, pdf
    folderitems:  

    - title: Current posts
      output: web
      url: /news.html

    - title: Post archive
      output: web
      url: /news_archive.html

    
# Copyright 2021 Google LLC